/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Control.ProfesoresController;
import Model.ProfesoresModel;
import java.util.Observable;

/**
 *
 * @author Josue
 */
public class ProfesoresView extends javax.swing.JInternalFrame implements java.util.Observer {

    /**
     * Creates new form ProfesoresView
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {

    }

    ProfesoresController controller;
    ProfesoresModel model;

    public void setController(ProfesoresController controller) {
        this.controller = controller;
    }

    public ProfesoresController getController() {
        return controller;
    }

    public void setModel(ProfesoresModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public ProfesoresView() {
        super("", false, true);
        initComponents();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
